# pages github defaults
safe: true
lsi: false
baseurl: ""
url: "https://montrehack.ca"

logo: "/images/montrehack.svg"
# OpenGraph/TwitterCard don't support svg logos
logo_opengraph: "/images/montrehack-fb.png"
logo_twittercard: "images/montrehack-tw.png"

# Publish posts or collection documents with a future date.
future: true

# exclude some files we don't want to leak
exclude: [ 'README.md', 'CNAME', 'TODO', 'Gemfile', 'Gemfile.lock', 'meta', 'vendor', 'scripts' ]

plugins:
  - jemoji
  - jekyll-feed
