name: Build website

on:
  - push
  - pull_request

jobs:
  build-site:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: helaili/jekyll-action@v2
      with:
         build_only: true
         pre_build_commands: "echo $PWD"
         target_branch: master
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: _site/
